"""Generate a user-friendly PDF report for a ScamShield analysis result."""

import io
import os
import re
from datetime import datetime, timezone

from fpdf import FPDF

PRIMARY = (79, 70, 229)
SCAM = (220, 38, 38)
CAUTION = (217, 119, 6)
SAFE = (22, 163, 74)
INK = (15, 23, 42)
MUTED = (100, 116, 139)
LINE = (226, 232, 240)

_STYLE_FILES = [
    ("", ("arial.ttf", "DejaVuSans.ttf", "LiberationSans-Regular.ttf")),
    ("B", ("arialbd.ttf", "DejaVuSans-Bold.ttf", "LiberationSans-Bold.ttf")),
    ("I", ("ariali.ttf", "DejaVuSans-Oblique.ttf", "LiberationSans-Italic.ttf")),
]


def _find_font_dir():
    candidates = [
        r"C:\Windows\Fonts",
        "/usr/share/fonts/truetype/dejavu",
        "/usr/share/fonts/dejavu",
        "/usr/share/fonts/truetype/liberation",
        "/usr/share/fonts/truetype/liberation2",
        "/usr/share/fonts/truetype/noto",
    ]
    for directory in candidates:
        if os.path.isdir(directory):
            return directory
    for root in ("/usr/share/fonts", "/usr/local/share/fonts"):
        if not os.path.isdir(root):
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            if "DejaVuSans.ttf" in filenames:
                return dirpath
            dirnames[:] = [d for d in dirnames if d not in ("opentype", "postscript")]
    try:
        import matplotlib

        bundled = os.path.join(matplotlib.get_data_path(), "fonts", "ttf")
        if os.path.isdir(bundled):
            return bundled
    except Exception:
        pass
    return None


_FONT_DIR_CACHE = None


def _font_dir():
    global _FONT_DIR_CACHE
    if _FONT_DIR_CACHE is None:
        _FONT_DIR_CACHE = os.environ.get("SCAMSHIELD_FONT_DIR") or _find_font_dir()
    return _FONT_DIR_CACHE


def _font_files():
    directory = _font_dir()
    if not directory:
        raise RuntimeError(
            "No TrueType font found for PDF report generation. Set SCAMSHIELD_FONT_DIR "
            "or install fonts-dejavu-core / Liberation fonts."
        )
    files = {}
    for style, names in _STYLE_FILES:
        for name in names:
            path = os.path.join(directory, name)
            if os.path.isfile(path):
                files[style] = path
                break
        else:
            raise FileNotFoundError(f"No font variant for style '{style}' in {directory}")
    return files


def _register_fonts(pdf):
    """Add TTF fonts to the PDF. Falls back to built-in core fonts if no
    .ttf file is available on the host (guarantees the PDF always builds)."""
    try:
        for style, path in _font_files().items():
            pdf.add_font("Arial", style, path)
        return "Arial"
    except Exception:
        return "Helvetica"


def score_meta(score):
    if score >= 0.7:
        return SCAM, "HIGH RISK", "likely a scam"
    if score >= 0.4:
        return CAUTION, "MEDIUM RISK", "may be suspicious"
    return SAFE, "LOW RISK", "likely legitimate"


def _sanitize(text, max_len=1800, enc=None):
    text = re.sub(r"<[^>]+>", "", text or "")
    for entity, char in (("&amp;", "&"), ("&lt;", "<"), ("&gt;", ">"), ("&quot;", '"')):
        text = text.replace(entity, char)
    text = re.sub(r"\s+", " ", text).strip()
    if enc:
        text = text.encode(enc, "replace").decode(enc)
    if len(text) > max_len:
        text = text[:max_len].rstrip() + "..."
    return text


class _Report(FPDF):
    def __init__(self, format="A4"):
        super().__init__(format=format)
        self.font_family = "Arial"

    def header(self):
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, self.w, 22, "F")
        self.set_font(self.font_family, "B", 15)
        self.set_text_color(255, 255, 255)
        self.set_xy(14, 6)
        self.cell(0, 10, "ScamShield", new_x="LMARGIN", new_y="NEXT")
        self.set_font(self.font_family, "", 9)
        self.set_text_color(224, 231, 255)
        self.cell(0, 5, "Job Posting Fraud Risk Report", new_x="LMARGIN", new_y="NEXT")

    def footer(self):
        self.set_y(-14)
        self.set_font(self.font_family, "I", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 8, "Generated by ScamShield - an AI-assisted scam detection tool. Not legal advice.", align="C")


def _severity_meta(severity):
    if severity >= 0.9:
        return SCAM, "CRITICAL"
    if severity >= 0.7:
        return CAUTION, "HIGH"
    return MUTED, "MEDIUM"


def _score_bar(pdf, label, value, color, family, width=174):
    y = pdf.get_y()
    pdf.set_font(family, "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 5, label, new_x="LMARGIN", new_y="NEXT")
    pdf.set_fill_color(*LINE)
    pdf.rect(14, y + 6, width, 4, "F")
    pct = max(0.0, min(1.0, value or 0))
    pdf.set_fill_color(*color)
    pdf.rect(14, y + 6, width * pct, 4, "F")
    pdf.set_font(family, "B", 9)
    pdf.set_text_color(*INK)
    pdf.set_xy(14 + width + 4, y + 4)
    pdf.cell(0, 6, f"{pct * 100:.0f}%")
    pdf.set_xy(14, y + 12)


def build_pdf_report(result, source_text="", title="ScamShield Analysis Report"):
    score = float(result.get("score", 0))
    color, verdict, verdict_note = score_meta(score)
    label = result.get("label", "")
    now = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")

    pdf = _Report(format="A4")
    family = _register_fonts(pdf)
    pdf.font_family = family
    sanitize = (lambda t, m=1800: _sanitize(t, m, enc="latin-1")) if family == "Helvetica" else _sanitize
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    pdf.set_font(family, "B", 13)
    pdf.set_text_color(*INK)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")

    y = pdf.get_y()
    pdf.set_fill_color(*color)
    pdf.rect(14, y + 2, 60, 24, "F")
    pdf.set_font(family, "B", 17)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, y + 6)
    pdf.cell(60, 10, f"{score * 100:.0f}%", align="C")
    pdf.set_font(family, "B", 7)
    pdf.set_xy(14, y + 16)
    pdf.cell(60, 8, verdict, align="C")

    pdf.set_xy(86, y + 3)
    pdf.set_font(family, "B", 12)
    pdf.set_text_color(*INK)
    pdf.cell(0, 7, f"Scam likelihood: {score * 100:.0f}%  ({label})")
    pdf.set_xy(86, y + 11)
    pdf.set_font(family, "", 9)
    pdf.set_text_color(*MUTED)
    pdf.set_x(86)
    pdf.multi_cell(114, 5, f"This posting is {verdict_note} (score 0-100).", new_x="LMARGIN")

    pdf.set_xy(86, y + 22)
    pdf.set_font(family, "", 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 5, f"Analyzed: {now}")
    if result.get("type"):
        pdf.cell(0, 5, f"   Source: {result.get('type')}")
    pdf.set_xy(14, y + 32)

    pdf.set_draw_color(*color)
    pdf.set_fill_color(255, 255, 255)
    pdf.rect(14, pdf.get_y(), 182, 2, "F")

    summary = result.get("explanation", {}).get("bullet_points", [])
    if summary:
        pdf.ln(3)
        pdf.set_font(family, "B", 11)
        pdf.set_text_color(*INK)
        pdf.cell(0, 7, "Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(family, "", 9.5)
        pdf.set_text_color(51, 65, 85)
        for bullet in summary:
            pdf.set_x(14)
            pdf.multi_cell(186, 5.5, f"  - {sanitize(str(bullet))}", new_x="LMARGIN")

    red_flags = result.get("red_flags") or []
    if red_flags:
        pdf.ln(2)
        pdf.set_font(family, "B", 11)
        pdf.set_text_color(*INK)
        pdf.cell(0, 7, f"Detected red flags ({len(red_flags)})", new_x="LMARGIN", new_y="NEXT")
        for flag in red_flags:
            sev_color, sev_label = _severity_meta(float(flag.get("severity", 0.5)))
            name = sanitize(str(flag.get("name", "")))
            explanation = sanitize(str(flag.get("explanation", "")))
            y0 = pdf.get_y()
            if y0 + 24 > pdf.h - 16:
                pdf.add_page()
                y0 = pdf.get_y()
            pdf.set_draw_color(*sev_color)
            pdf.set_fill_color(250, 250, 252)
            pdf.set_line_width(1.1)
            pdf.rect(14, y0, 182, 2, "F")
            pdf.rect(14, y0 + 3, 182, 22, "DF")
            pdf.set_line_width(0.2)
            pdf.set_xy(20, y0 + 4)
            pdf.set_font(family, "B", 9.5)
            pdf.set_text_color(*sev_color)
            pdf.cell(0, 6, name)
            pdf.set_xy(20, y0 + 11)
            pdf.set_font(family, "", 8.5)
            pdf.set_text_color(80, 40, 40)
            pdf.multi_cell(168, 4.5, explanation, new_x="LMARGIN")
            evidence = flag.get("evidence") or []
            if evidence:
                pdf.set_xy(20, pdf.get_y() + 1)
                pdf.set_font(family, "", 8)
                pdf.set_text_color(*MUTED)
                pdf.multi_cell(168, 4, "Evidence: " + ", ".join(sanitize(str(e), 120) for e in evidence), new_x="LMARGIN")
            pdf.set_xy(170, y0 + 4)
            pdf.set_font(family, "B", 8)
            pdf.set_text_color(255, 255, 255)
            pdf.set_fill_color(*sev_color)
            pdf.cell(22, 6, sev_label, align="C", fill=True)
            pdf.ln(8)

    scores = [("Rule engine score", result.get("rule_score")),
              ("AI model confidence", result.get("model_confidence")),
              ("Known-template match", result.get("duplicate_template_score"))]
    present = [(n, v) for n, v in scores if v is not None]
    if present:
        pdf.ln(2)
        pdf.set_font(family, "B", 11)
        pdf.set_text_color(*INK)
        pdf.cell(0, 7, "Score breakdown", new_x="LMARGIN", new_y="NEXT")
        for name, value in present:
            _score_bar(pdf, name, float(value), color, family)

    source = sanitize(source_text or result.get("ocr_text") or "")
    if source:
        if pdf.get_y() + 40 > pdf.h - 16:
            pdf.add_page()
        pdf.ln(2)
        pdf.set_font(family, "B", 11)
        pdf.set_text_color(*INK)
        pdf.cell(0, 7, "Analyzed posting", new_x="LMARGIN", new_y="NEXT")
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(*LINE)
        pdf.set_x(14)
        pdf.multi_cell(186, 5.5, source, border=1, fill=True, new_x="LMARGIN")

    pdf.set_font(family, "I", 7.5)
    pdf.set_text_color(*MUTED)
    pdf.ln(3)
    pdf.set_x(14)
    pdf.multi_cell(
        186, 4,
        "How to read this report: the scam-likelihood score estimates how closely the "
        "posting matches known fraud patterns (fee/security-deposit requests, too-good "
        "salaries, generic email/WhatsApp contacts, urgency pressure). A high score does "
        "not prove fraud - always verify the employer directly before paying anything.",
        new_x="LMARGIN",
    )

    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
